# -*- coding: utf-8 -*-
"""slopecsvD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a8qU1S3NT4QtLW59roJogmu_rWaxAyUB
"""

from google.colab import drive
drive.mount('/content/drive') #This will require you enter passcode to access your drive
path='/content/drive/My Drive/FIB 4 FAB/RCWA code/rcwa/examples/csvs'



import numpy as np
def Slopecsv(res,theta,depthF, material, gType, er): #depth is fraction of wavelength
  nm= 10**(-9)
  um=10**(-6)
  duty=0.5
  

  ##refractive index vals at 400nm
  Air_n = 1.000536
  Si_n = 5.623
  Al_n = 0.375150842
  Ag_n = 0.04572895
 



  #extinction coefficient vals at 400nm
  Air_k = 1.00000037
  Si_k = 0.326
  Al_k= 4.226433266
  Ag_k = 2.122943979

  if material == 'Silicon':
    mat_e=np.square(Si_n)
    print('grating material = silicon')
  elif material == 'Aluminium':
    mat_e=np.square(Al_n)
    print('grating material = aluminium')

  elif material == 'Silver':
    mat_e=np.square(Ag_n)
    print('grating material = silver')
  mat_u=1
  e=1.0006
  u= 1

  arr=np.ones([res,res])
  Uarr=arr
  arr=(1+0j)*arr
  print(theta)
  if theta > 0:
      print(f"slopey")
      thetaR=np.deg2rad(theta)
      nLayer=int(np.divide(2,3)*res*depthF*np.tan(thetaR))
      arrE=er*arr
      arrU=mat_u*arr
      count=0
      i=0
      j=int(res/4)
      while count <= nLayer:
        arrE=er*arr
        arrU=mat_u*arr
        i=0
        j=int(res/4+count)
        #permittivity
        while i <res:
            while j >= res/4+count and j < 3*res/4-count: 
                arrE[i,j]=e
                arrU[i,j]=u
                j=j+1
            j=int(res/4+count)
            i=i+1
            
            
        np.savetxt(f'{path}/{gType}_{material}_slope{theta}_{depthF}_layer{count}_{res}.csv', arrE, delimiter=',')
        np.savetxt(f'{path}/U{res}.csv', Uarr, delimiter=',')
    
        
    
        count=count+1
  elif theta ==0:
    print('verticaLL')
    count=0
    nLayer=1
    i,j=0,int(res/4)
    arrE=er*arr
    arrU=mat_u*arr
    while i < res:
        
        while j>=int(res/4) and j < int(3*res/4):
            arrE[j,i]=e
            arrU[j,i]=u
            j=j+1
        j=int(res/4)
        i=i+1
    np.savetxt(f'{path}/{gType}_{material}_slope0.0_layer0_{res}.csv', arrE, delimiter=',')
    np.savetxt(f'{path}/U{res}.csv', Uarr, delimiter=',')
  else:
    print('Theta must be >=0')
  return nLayer



